/* Alimentos para armar un plato a mano en el Menú.
   Valores aproximados por 100 g (o 100 ml) de parte comestible: p proteína, c carbohidratos netos, f grasa.
   k: calorías por 100 solo cuando llevan alcohol (si no, se calculan con 4·p + 4·c + 9·f).
   u: medidas caseras [nombre, gramos, plural]. d: cantidad y medida al añadirlo. l: líquido (se mide en ml).
   a: otras palabras con las que se puede buscar. Fuentes: BEDCA, USDA y etiquetas de supermercado en España. */
var ALIMENTOS = [
  /* Huevos, carne y embutido */
  {id:'huevo', n:'Huevo', p:12.6, c:0.7, f:9.9, u:[['huevo',55,'huevos']], d:[1,'huevo'], a:'huevos tortilla revuelto frito cocido'},
  {id:'clara', n:'Clara de huevo', p:10.9, c:0.7, f:0.2, u:[['clara',33,'claras']], d:[2,'clara'], a:'claras'},
  {id:'pechuga', n:'Pechuga de pollo (cruda)', p:23, c:0, f:1.5, d:[150,'g'], a:'pollo filete'},
  {id:'pollo-cocinado', n:'Pollo cocinado sin piel', p:31, c:0, f:4, d:[100,'g'], a:'pollo asado desmechado desmenuzado a la plancha'},
  {id:'contramuslo', n:'Contramuslo de pollo sin hueso (crudo)', p:19.5, c:0, f:6, d:[150,'g'], a:'pollo muslo'},
  {id:'pavo', n:'Pechuga de pavo (cruda)', p:22, c:0, f:1.5, d:[150,'g'], a:'pavo filete'},
  {id:'pavo-fiambre', n:'Pavo en lonchas o taquitos', p:19, c:1.5, f:2, u:[['loncha',15,'lonchas']], d:[50,'g'], a:'fiambre pavo'},
  {id:'jamon-york', n:'Jamón cocido (york)', p:18, c:1, f:3, u:[['loncha',15,'lonchas']], d:[50,'g'], a:'jamon york fiambre'},
  {id:'jamon-serrano', n:'Jamón serrano', p:30, c:0, f:13, u:[['loncha',15,'lonchas']], d:[3,'loncha'], a:'jamon iberico'},
  {id:'cecina', n:'Cecina', p:38, c:0.5, f:8, u:[['loncha',10,'lonchas']], d:[50,'g']},
  {id:'chorizo', n:'Chorizo', p:24, c:2, f:35, d:[30,'g'], a:'embutido salchichon'},
  {id:'bacon', n:'Bacon o panceta', p:13, c:1, f:40, u:[['loncha',15,'lonchas']], d:[2,'loncha'], a:'tocineta beicon'},
  {id:'ternera-picada', n:'Carne picada de ternera (cruda)', p:18.5, c:0, f:15, d:[150,'g'], a:'carne molida hamburguesa'},
  {id:'ternera-filete', n:'Filete de ternera (crudo)', p:21, c:0, f:5, d:[150,'g'], a:'carne bistec res'},
  {id:'entrecot', n:'Entrecot o chuletón (crudo)', p:19.5, c:0, f:15, d:[250,'g'], a:'carne res'},
  {id:'cerdo-lomo', n:'Lomo de cerdo (crudo)', p:20, c:0, f:8, d:[150,'g'], a:'cerdo'},
  {id:'cerdo-solomillo', n:'Solomillo de cerdo (crudo)', p:21, c:0, f:3.5, d:[150,'g'], a:'cerdo'},
  {id:'cerdo-picada', n:'Carne picada de cerdo (cruda)', p:17, c:0, f:20, d:[150,'g'], a:'cerdo molida'},
  {id:'cabra', n:'Carne de cabra sin hueso (cruda)', p:20.6, c:0, f:2.3, d:[150,'g'], a:'cabra baifo'},
  {id:'conejo', n:'Conejo sin hueso (crudo)', p:20, c:0, f:5.5, d:[150,'g']},
  {id:'cordero', n:'Cordero sin hueso (crudo)', p:18, c:0, f:14, d:[150,'g']},
  /* Pescado y marisco */
  {id:'salmon', n:'Salmón (crudo)', p:20, c:0, f:13, d:[150,'g']},
  {id:'salmon-ahumado', n:'Salmón ahumado', p:22, c:0, f:10, d:[50,'g']},
  {id:'atun-fresco', n:'Atún fresco (crudo)', p:23, c:0, f:3, d:[150,'g']},
  {id:'atun-aceite', n:'Atún en lata con aceite (escurrido)', p:26, c:0, f:8, u:[['lata',52,'latas']], d:[1,'lata'], a:'atun lata'},
  {id:'atun-natural', n:'Atún en lata al natural (escurrido)', p:24, c:0, f:1, u:[['lata',52,'latas']], d:[1,'lata'], a:'atun lata'},
  {id:'merluza', n:'Merluza (cruda)', p:17, c:0, f:1.5, d:[150,'g'], a:'pescado blanco'},
  {id:'pescado-blanco', n:'Lubina, dorada o corvina (cruda)', p:19, c:0, f:3, d:[150,'g'], a:'pescado blanco sama cherne vieja'},
  {id:'bacalao', n:'Bacalao desalado', p:18, c:0, f:0.7, d:[150,'g'], a:'pescado'},
  {id:'caballa', n:'Caballa o chicharro (filete)', p:19, c:0, f:9, d:[150,'g'], a:'pescado azul'},
  {id:'sardinas', n:'Sardinas en lata con aceite (escurridas)', p:25, c:0, f:11, u:[['lata',60,'latas']], d:[1,'lata'], a:'sardina'},
  {id:'langostinos', n:'Langostinos o gambas (pelados)', p:19, c:0, f:1, d:[150,'g'], a:'camarones marisco'},
  {id:'pulpo', n:'Pulpo cocido', p:18, c:1, f:1.5, d:[150,'g'], a:'marisco'},
  {id:'calamar', n:'Calamar o chipirones (crudos)', p:15.6, c:3, f:1.4, d:[150,'g'], a:'marisco sepia choco'},
  {id:'mejillones', n:'Mejillones sin concha (cocidos)', p:24, c:7, f:4.5, d:[100,'g'], a:'marisco'},
  /* Lácteos y quesos */
  {id:'queso-fresco', n:'Queso fresco (tipo Burgos)', p:13, c:3, f:14, d:[100,'g'], a:'queso blanco burgos'},
  {id:'queso-batido', n:'Queso fresco batido 0 %', p:8, c:3.5, f:0.2, d:[150,'g'], a:'queso batido'},
  {id:'skyr', n:'Skyr o yogur alto en proteína', p:11, c:4, f:0.3, d:[150,'g'], a:'yogur proteico proteina'},
  {id:'yogur', n:'Yogur natural', p:3.8, c:4.7, f:3.2, u:[['yogur',125,'yogures']], d:[1,'yogur']},
  {id:'yogur-griego', n:'Yogur griego natural sin azúcar', p:6, c:4, f:10, u:[['yogur',125,'yogures']], d:[1,'yogur']},
  {id:'cottage', n:'Queso cottage', p:11, c:3.4, f:4.3, d:[100,'g']},
  {id:'queso-semi', n:'Queso semicurado', p:24, c:0.5, f:29, d:[40,'g'], a:'queso tierno'},
  {id:'queso-cabra', n:'Queso de cabra semicurado (herreño)', p:23, c:0.5, f:30, d:[40,'g'], a:'queso herreño majorero palmero'},
  {id:'queso-curado', n:'Queso curado (manchego)', p:27, c:0.5, f:33, d:[30,'g'], a:'queso viejo'},
  {id:'queso-lonchas', n:'Queso en lonchas (gouda, edam)', p:25, c:0, f:27, u:[['loncha',20,'lonchas']], d:[2,'loncha'], a:'queso amarillo'},
  {id:'mozzarella', n:'Mozzarella fresca', p:18, c:2, f:18, u:[['bola',125,'bolas']], d:[0.5,'bola']},
  {id:'queso-rallado', n:'Queso rallado para gratinar', p:25, c:1, f:27, u:[['cda',7,'cdas']], d:[30,'g']},
  {id:'parmesano', n:'Parmesano', p:35, c:0, f:28, u:[['cda',6,'cdas']], d:[20,'g']},
  {id:'queso-crema', n:'Queso crema (tipo Philadelphia)', p:6, c:4, f:25, u:[['cda',15,'cdas']], d:[1,'cda']},
  {id:'leche-entera', n:'Leche entera', l:1, p:3.2, c:4.7, f:3.6, u:[['vaso',250,'vasos']], d:[1,'vaso']},
  {id:'leche-semi', n:'Leche semidesnatada', l:1, p:3.3, c:4.8, f:1.6, u:[['vaso',250,'vasos']], d:[1,'vaso']},
  {id:'leche-desnatada', n:'Leche desnatada', l:1, p:3.4, c:4.9, f:0.2, u:[['vaso',250,'vasos']], d:[1,'vaso']},
  {id:'bebida-almendra', n:'Bebida de almendras sin azúcar', l:1, p:0.4, c:0, f:1.1, u:[['vaso',250,'vasos']], d:[1,'vaso'], a:'leche de almendras'},
  {id:'kefir', n:'Kéfir natural', l:1, p:3.3, c:4, f:3.3, u:[['vaso',250,'vasos']], d:[1,'vaso']},
  {id:'nata-cocinar', n:'Nata para cocinar', p:2.5, c:3.5, f:18, u:[['cda',15,'cdas']], d:[2,'cda'], a:'crema de leche'},
  {id:'nata-montar', n:'Nata para montar (35 %)', p:2, c:3, f:35, u:[['cda',15,'cdas']], d:[2,'cda'], a:'crema de leche'},
  {id:'mantequilla', n:'Mantequilla', p:0.9, c:0, f:81, u:[['cdta',5,'cdtas'], ['cda',14,'cdas']], d:[1,'cdta']},
  {id:'whey', n:'Proteína whey', p:80, c:7, f:6, u:[['cazo',30,'cazos']], d:[1,'cazo'], a:'proteina en polvo batido'},
  {id:'tofu', n:'Tofu firme', p:15, c:1.5, f:8, d:[100,'g']},
  /* Verduras */
  {id:'puerro', n:'Puerro', p:1.5, c:12.3, f:0.3, u:[['unidad',90,'unidades']], d:[1,'unidad']},
  {id:'cebolla', n:'Cebolla', p:1.1, c:7.6, f:0.1, u:[['unidad',150,'unidades']], d:[0.5,'unidad'], a:'cebolla morada cebolleta'},
  {id:'ajo', n:'Ajo', p:6.4, c:31, f:0.5, u:[['diente',4,'dientes']], d:[1,'diente']},
  {id:'tomate', n:'Tomate', p:0.9, c:2.7, f:0.2, u:[['unidad',120,'unidades']], d:[1,'unidad']},
  {id:'tomate-cherry', n:'Tomates cherry', p:0.9, c:2.7, f:0.2, u:[['unidad',15,'unidades']], d:[6,'unidad']},
  {id:'tomate-triturado', n:'Tomate triturado natural', p:1.3, c:3.5, f:0.2, d:[100,'g']},
  {id:'tomate-frito', n:'Tomate frito', p:1.6, c:11, f:3.5, u:[['cda',15,'cdas']], d:[2,'cda'], a:'salsa de tomate'},
  {id:'pimiento-rojo', n:'Pimiento rojo', p:1, c:4.6, f:0.3, u:[['unidad',180,'unidades']], d:[0.5,'unidad'], a:'pimenton'},
  {id:'pimiento-verde', n:'Pimiento verde', p:0.9, c:2.9, f:0.2, u:[['unidad',160,'unidades']], d:[0.5,'unidad'], a:'pimenton'},
  {id:'calabacin', n:'Calabacín', p:1.2, c:2.1, f:0.3, u:[['unidad',200,'unidades']], d:[0.5,'unidad'], a:'zucchini'},
  {id:'berenjena', n:'Berenjena', p:1, c:2.9, f:0.2, u:[['unidad',300,'unidades']], d:[0.5,'unidad']},
  {id:'espinacas', n:'Espinacas', p:2.9, c:1.4, f:0.4, u:[['puñado',30,'puñados']], d:[2,'puñado']},
  {id:'champinones', n:'Champiñones o setas', p:3.1, c:2.3, f:0.3, d:[100,'g'], a:'hongos'},
  {id:'brocoli', n:'Brócoli', p:2.8, c:4, f:0.4, d:[150,'g']},
  {id:'coliflor', n:'Coliflor', p:1.9, c:3, f:0.3, d:[150,'g'], a:'arroz de coliflor'},
  {id:'judias', n:'Judías verdes', p:1.8, c:4.3, f:0.2, d:[150,'g'], a:'vainitas'},
  {id:'esparragos', n:'Espárragos trigueros', p:2.2, c:1.8, f:0.1, d:[100,'g']},
  {id:'lechuga', n:'Lechuga o mezcla de hojas', p:1.2, c:1.5, f:0.2, u:[['puñado',30,'puñados']], d:[80,'g'], a:'ensalada rucula canonigos'},
  {id:'pepino', n:'Pepino', p:0.7, c:3, f:0.1, u:[['unidad',300,'unidades']], d:[0.5,'unidad']},
  {id:'zanahoria', n:'Zanahoria', p:0.9, c:7, f:0.2, u:[['unidad',80,'unidades']], d:[1,'unidad']},
  {id:'calabaza', n:'Calabaza', p:1, c:6.5, f:0.1, d:[150,'g'], a:'auyama'},
  {id:'col', n:'Col o repollo', p:1.3, c:3.3, f:0.1, d:[150,'g']},
  {id:'palmitos', n:'Palmitos en conserva (escurridos)', p:2.5, c:2.2, f:0.6, d:[100,'g'], a:'palmito corazones de palma'},
  {id:'esparragos-blancos', n:'Espárragos blancos en conserva', p:1.8, c:2, f:0.2, u:[['unidad',30,'unidades']], d:[6,'unidad'], a:'esparrago blanco'},
  {id:'aguacate', n:'Aguacate', p:2, c:1.8, f:15, u:[['unidad',150,'unidades']], d:[0.5,'unidad'], a:'palta'},
  {id:'aceitunas', n:'Aceitunas', p:0.8, c:0.5, f:15, u:[['unidad',4,'unidades']], d:[8,'unidad']},
  /* Grasas, frutos secos y salsas */
  {id:'aceite', n:'Aceite de oliva', p:0, c:0, f:100, u:[['cda',13.5,'cdas'], ['cdta',4.5,'cdtas']], d:[1,'cda']},
  {id:'almendras', n:'Almendras', p:21, c:9, f:50, u:[['puñado',30,'puñados']], d:[1,'puñado'], a:'frutos secos'},
  {id:'nueces', n:'Nueces', p:15, c:7, f:65, u:[['puñado',30,'puñados']], d:[1,'puñado'], a:'frutos secos'},
  {id:'cacahuetes', n:'Cacahuetes', p:26, c:7.6, f:49, u:[['puñado',30,'puñados']], d:[1,'puñado'], a:'mani frutos secos'},
  {id:'crema-cacahuete', n:'Crema de cacahuete', p:25, c:12, f:50, u:[['cda',16,'cdas']], d:[1,'cda'], a:'mantequilla de mani'},
  {id:'chia', n:'Semillas de chía', p:17, c:8, f:31, u:[['cda',12,'cdas']], d:[1,'cda']},
  {id:'mayonesa', n:'Mayonesa', p:1, c:1, f:75, u:[['cda',14,'cdas']], d:[1,'cda']},
  {id:'mojo', n:'Mojo rojo o verde', p:1, c:3.5, f:45, u:[['cda',15,'cdas']], d:[1,'cda']},
  {id:'guasacaca', n:'Guasacaca', p:1, c:2, f:25, u:[['cda',15,'cdas']], d:[2,'cda']},
  {id:'salsa-soja', n:'Salsa de soja', p:8, c:5, f:0, u:[['cda',16,'cdas']], d:[1,'cda']},
  {id:'ketchup', n:'Kétchup', p:1.2, c:25, f:0.1, u:[['cda',17,'cdas']], d:[1,'cda']},
  {id:'chocolate', n:'Chocolate negro 85 %', p:10, c:14, f:46, u:[['onza',10,'onzas']], d:[2,'onza']},
  /* Con moderación: carbohidratos y fruta */
  {id:'casabe', n:'Casabe', p:1.3, c:80, f:0.5, u:[['trozo',15,'trozos']], d:[1,'trozo']},
  {id:'arepa', n:'Arepa', p:4.4, c:42, f:1, u:[['unidad',90,'unidades']], d:[1,'unidad']},
  {id:'pan', n:'Pan blanco o de barra', p:8.5, c:49, f:1.5, u:[['rebanada',30,'rebanadas']], d:[1,'rebanada'], a:'bocadillo tostada'},
  {id:'pan-integral', n:'Pan integral', p:10, c:40, f:3.5, u:[['rebanada',30,'rebanadas']], d:[1,'rebanada'], a:'tostada'},
  {id:'arroz', n:'Arroz blanco cocido', p:2.7, c:28, f:0.3, u:[['taza',160,'tazas']], d:[0.5,'taza']},
  {id:'pasta', n:'Pasta cocida', p:5.8, c:29, f:0.9, u:[['taza',140,'tazas']], d:[1,'taza'], a:'macarrones espaguetis fideos'},
  {id:'papa', n:'Papa o patata cocida', p:2, c:15.5, f:0.1, u:[['unidad',170,'unidades']], d:[1,'unidad'], a:'patata papas arrugadas'},
  {id:'papas-fritas', n:'Papas fritas', p:3.4, c:37, f:15, u:[['ración',150,'raciones']], d:[1,'ración'], a:'patatas fritas'},
  {id:'batata', n:'Batata o boniato', p:1.6, c:17, f:0.1, d:[150,'g'], a:'camote'},
  {id:'platano-macho', n:'Plátano macho frito (tajadas)', p:1.5, c:38, f:12, d:[100,'g'], a:'tajadas tostones'},
  {id:'avena', n:'Copos de avena', p:13, c:58, f:7, u:[['cda',10,'cdas']], d:[40,'g'], a:'avena'},
  {id:'gofio', n:'Gofio', p:10, c:63, f:3, u:[['cda',12,'cdas']], d:[2,'cda']},
  {id:'lentejas', n:'Lentejas cocidas', p:9, c:12, f:0.4, d:[150,'g']},
  {id:'garbanzos', n:'Garbanzos cocidos', p:8.9, c:19, f:2.6, d:[150,'g']},
  {id:'alubias', n:'Alubias o caraotas cocidas', p:8.7, c:16.4, f:0.5, d:[150,'g'], a:'frijoles judias caraotas negras'},
  {id:'platano', n:'Plátano o banana', p:1.1, c:20, f:0.3, u:[['unidad',120,'unidades']], d:[1,'unidad'], a:'cambur'},
  {id:'kiwi', n:'Kiwi', p:1.1, c:11.7, f:0.5, u:[['unidad',70,'unidades']], d:[1,'unidad']},
  {id:'manzana', n:'Manzana', p:0.3, c:12, f:0.2, u:[['unidad',180,'unidades']], d:[1,'unidad']},
  {id:'naranja', n:'Naranja', p:0.9, c:9.4, f:0.1, u:[['unidad',150,'unidades']], d:[1,'unidad']},
  {id:'fresas', n:'Fresas', p:0.7, c:5.7, f:0.3, d:[100,'g']},
  {id:'frutos-rojos', n:'Frambuesas o arándanos', p:1, c:8, f:0.6, d:[60,'g']},
  {id:'papaya', n:'Papaya', p:0.5, c:9, f:0.3, d:[150,'g'], a:'lechosa'},
  {id:'pina', n:'Piña', p:0.5, c:11.7, f:0.1, d:[150,'g']},
  {id:'mango', n:'Mango', p:0.8, c:13.4, f:0.4, d:[150,'g']},
  {id:'azucar', n:'Azúcar', p:0, c:100, f:0, u:[['cdta',5,'cdtas']], d:[1,'cdta']},
  {id:'miel', n:'Miel', p:0.3, c:82, f:0, u:[['cdta',7,'cdtas']], d:[1,'cdta']},
  /* Bebidas */
  {id:'cerveza', n:'Cerveza', l:1, p:0.4, c:3.6, f:0, k:43, u:[['caña',200,'cañas'], ['lata',330,'latas']], d:[1,'caña']},
  {id:'cerveza-sin', n:'Cerveza sin alcohol', l:1, p:0.3, c:5, f:0, u:[['caña',200,'cañas'], ['lata',330,'latas']], d:[1,'caña']},
  {id:'vino', n:'Vino tinto o blanco', l:1, p:0.1, c:2.6, f:0, k:85, u:[['copa',150,'copas']], d:[1,'copa']},
  {id:'licor', n:'Ron, whisky o ginebra', l:1, p:0, c:0, f:0, k:230, u:[['copa',50,'copas']], d:[1,'copa'], a:'cubata combinado'},
  {id:'refresco', n:'Refresco con azúcar', l:1, p:0, c:10.6, f:0, u:[['lata',330,'latas']], d:[1,'lata'], a:'cola'},
  {id:'zumo', n:'Zumo de naranja', l:1, p:0.7, c:10, f:0.2, u:[['vaso',200,'vasos']], d:[1,'vaso'], a:'jugo'}
];
/* Los que salen primero, antes de buscar */
var ALIMENTOS_TOP = ['huevo', 'clara', 'pechuga', 'pollo-cocinado', 'queso-fresco', 'jamon-serrano', 'atun-natural', 'skyr', 'aguacate', 'aceite', 'puerro', 'tomate', 'cebolla', 'espinacas', 'casabe'];
